# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Bernoulli
tagline:          'Lving aboard on the Devonshire coast'
description:      'A diary of life aboard the Southerly 105 &ldquo;Bernoulli&rdquo;, based in Plymouth, UK.'
url:              http://sajseven.github.io/bernoulli
baseurl:          '/bernoulli/'

author:
  name:           'Stephen Jarman'
  url:            https://sajseven.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sajseven/bernoulli
